# 텐서
![텐서(Tensor)형태](https://codetorial.net/tensorflow/_images/basics_of_tensor_01.png)

In [2]:
# Numpy의 array()를 이용해서 텐서 형태 확인
# 스칼라(scala)텐서 -> 0차원 텐서, 0D텐서, rank0인 텐서라고 다양하게 칭함
# 하나의 숫자만 담고 있는 텐서
# 하나의 값을 가지는 일반변수라고 생각하면 이해편하다

import numpy as np

x = np.array(12)
print("스칼라 텐서 : ", x)
print("차원 : ", x.shape)
print("rank 확인 : ", x.ndim)

스칼라 텐서 :  12
차원 :  ()
rank 확인 :  0


In [3]:
# 벡터(vextor) 텐서 : 1D텐서, rank1 텐서
# 여러 숫자를 담고 있는 1차원 배열
# 1차원 리스트 []와 유사한 형태

x = np.array([12,3,6,14,7])
print("5개의 값을 가지는 벡터 : ", x)
print("차원 : ", x.shape)
print("rank 확인 : ", x.ndim)

5개의 값을 가지는 벡터 :  [12  3  6 14  7]
차원 :  (5,)
rank 확인 :  1


In [4]:
x[2]

6

In [5]:
# 행렬(Matrix) 텐서 : 2D텐서, rank2 텐서
# 여러개의 벡터(Vector)를 담고 있는 새로운 배열을 행렬(Matrix) 텐서라 칭함
# 2차원 : [[]] 형태
# 데이터프레임 형태와 유사
x = np.array([[5,78,2,34,0],
              [6,79,3,35,1],
              [7,80,4,36,2]])
print("행렬(matrix) : ", x)
print("차원 : ", x.shape)
print("rank 확인 : ", x.ndim)

행렬(matrix) :  [[ 5 78  2 34  0]
 [ 6 79  3 35  1]
 [ 7 80  4 36  2]]
차원 :  (3, 5)
rank 확인 :  2


In [11]:
x[:,0]

array([5, 6, 7])

In [12]:
# 3D 텐서 : rank3 텐서
# 행렬(matrix)이 여러개 모여있는것
# 숫자가 채워진 직육면체
x = np.array([[[5,78,2,34,0],[6,79,3,35,1],[7,80,4,36,2]],
              [[8,78,2,34,0],[9,79,3,35,1],[10,80,4,36,2]],
              [[11,78,2,34,0],[12,79,3,35,1],[13,80,4,36,2]]])
print("3D 텐서 : ", x)
print("차원 : ", x.shape)
print("rank 확인 : ", x.ndim)

3D 텐서 :  [[[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 8 78  2 34  0]
  [ 9 79  3 35  1]
  [10 80  4 36  2]]

 [[11 78  2 34  0]
  [12 79  3 35  1]
  [13 80  4 36  2]]]
차원 :  (3, 3, 5)
rank 확인 :  3


In [13]:
x[1,1,:]

array([ 9, 79,  3, 35,  1])